name: resact
channels:
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - absl-py
  - pyparsing
  - pip:
    - termcolor
    - dm-control
    - git+https://github.com/denisyarats/dmc2gym.git
    - opencv-python
    - pillow
    - scikit-image
    - scikit-video
    - tb-nightly
    - tqdm
    - imageio
    - imageio-ffmpeg
    - pygame
    - networkx
    - dotmap
    - torch==1.7.1+cu110
    - torchvision==0.8.2+cu110
    - torchaudio==0.7.2
    - gym==0.17.3
